#!/bin/sh
#-------------------------------------------------
#
# Copyright (C) 2015 TASER International, Inc.
# All Rights Reserved
# TASER Data Classification: CONFIDENTIAL
#
# WARNING: do not add .sh extension to the name of the script,
#          otherwise ifup will not run it.
#
# This script updates DNS configuration when WAN interface is up.

. /etm/bin/etm-net-common.sh

readonly RESOLV_CONF="/etc/resolv.conf"
readonly SCRIPT_NAME="ifup-wan-dns"

# IFACE is an environment variable set by ifup with the name of current network interface.
if [[ "${IFACE}" == "${WAN_IFACE}" ]] ; then
    log_info_msg "${SCRIPT_NAME}" "${IFACE} is up, it's a WAN interface"
    # read configuration of WAN interface
    WAN_IFACE_CFG="$(awk -f /etm/bin/queryInterfaces.awk /etc/network/interfaces device="${IFACE}")"
    if [[ ! -z "${WAN_IFACE_CFG}" ]] ; then
        # detect if WAN interface has static configuration
        if echo "${WAN_IFACE_CFG}" | grep -e "proto static" >/dev/null ; then
            log_info_msg "${SCRIPT_NAME}" "${IFACE} is configured as static, resetting ${RESOLV_CONF}"
            # if configuration contains two DNS servers then DNS_CFG would be:
            #   10.17.10.1 8.8.8.8
            # or in case of single DNS server:
            #   10.17.10.1
            DNS_CFG="$(echo "${WAN_IFACE_CFG}" | grep "dns" | awk '{print $2, $3}')"
            if [[ -z "${DNS_CFG}" ]] ; then
                log_err_msg "${SCRIPT_NAME}" "DNS configuration is empty"
            fi

            # if DNS_CFG is empty then update_dns_config() will only erase current DNS configuration
            if ! update_dns_cfg "${SCRIPT_NAME}" "${DNS_CFG}" ; then
                log_err_msg "${SCRIPT_NAME}" "failed to update DNS configuration"
                exit 1
            fi
        else
            log_verbose "${SCRIPT_NAME}" "${IFACE} is not configured as static"
        fi
    else
        log_err_msg "${SCRIPT_NAME}" "${IFACE} interface configuration is empty"
    fi
else
    log_verbose "${SCRIPT_NAME}" "${IFACE} is up, but not a WAN interface"
fi
